---
- hosts: all
  become: true
  tasks:
  - name: removing old war file
    file:
      path: /opt/tomcat9/webapps/myweb.war
      state: absent
  - name: deploy war file
    get_url:
    url: http://192.168.56.15:8081/repository/snapshots/www/webapp/${MY_BUILD_VERSION}/webapp-${MY_BUILD_VERSION}.war
    dest: /opt/tomcat9/webapps/myweb.war
    url_username: admin
    url_password: admin123
