---
- hosts: all
  become: true
  tasks:
  - name: removing old war file
    file:
      path: /opt/tomcat9/webapps/WebApp*.war
      state: absent
  - name: deploy war file
    shell: wget --user=admin --password='admin123' http://192.168.56.15:8081/repository/snapshots/www/webapp/${MY_BUILD_VERSION}/webapp-${MY_BUILD_VERSION}.war -o /opt/tomcat9/webapps/myapp.war
