---
- hosts: all
  become: true
  tasks:
  - name: removing old war file
    file:
      path: /opt/tomcat9/webapps/myapp.war
      state: absent
  - name: deploy war file
    get_url:
      url:http://192.168.56.15:8081/repository/snapshots/www/WebApp/1.0.0-SNAPSHOT/WebApp-1.0.0-20190630.083127-1.war
      dest: /opt/tomcat9/webapps/myapp.war
      username: admin
      password: admin123
